# docker-compose.yml
# create a keycloak container pointing to a mysql database container

volumes:
  # create a volume for mysql data (using local driver): keycloak-firebase-scrypt_mysql_data
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:8.4
    container_name: keycloak-firebase-scrypt-mysql
    volumes:
      - mysql_data:/var/lib/mysql
      # add any custom mysql configuration here (e.g. ./docker/mysql_conf_d/custom-mysql.cnf)
      - ./docker/mysql_conf_d/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_KC_DATABASE:-keycloak}
      MYSQL_USER: ${MYSQL_KC_USER:-keycloak}
      MYSQL_PASSWORD: ${MYSQL_KC_PASSWORD:-keycloakpass}
    hostname: mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  keycloak:
#    image: quay.io/keycloak/keycloak:26.4.6
    build: ./docker
    container_name: keycloak-firebase-scrypt-keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: ${MYSQL_KC_DATABASE:-keycloak}
      KC_DB_URL_PROPERTIES: "?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true"
      KC_DB_USERNAME: ${MYSQL_KC_USER:-keycloak}
      KC_DB_PASSWORD: ${MYSQL_KC_PASSWORD:-keycloakpass}

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}

      KC_HOSTNAME_STRICT: false
      KC_PROXY_HEADERS: xforwarded
      KC_PROXY: edge # Recommended when Keycloak is behind a reverse proxy
      KC_LOG: console,file,syslog
      KC_HTTP_ENABLED: true
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HOSTNAME_DEBUG: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_MANAGEMENT_PORT: 9000
    depends_on:
      mysql:
        condition: service_healthy
    hostname: keycloak
    ports:
      - 8080:8080
    command: [ "start"
#                ,
#               "--hostname=localhost",
#               "--http-enabled=true",
#               "--hostname-strict=false",
#               "--db=$${KC_DB}",
#               "--db-url-host=$${KC_DB_URL_HOST}",
#               "--db-url=jdbc:mysql://$${KC_DB_URL_HOST}:3306/$${KC_DB_URL_DATABASE}?characterEncoding=UTF-8",
#               "--db-username=$${KC_DB_USERNAME}",
#               "--db-password=$${KC_DB_PASSWORD}",
#               "--http-relative-path=$${KC_HTTP_RELATIVE_PATH}"
            ] # [ "start-dev" ]
    healthcheck:
      test: ["CMD-SHELL", "{ printf 'HEAD /auth/health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
